apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-scheduler
spec:
  selector:
    matchLabels:
      app: task-scheduler
  replicas: 2
  template:
    metadata:
      labels:
        app: task-scheduler
    spec:
      containers:
      - name: task-scheduler
        image: ghcr.io/michalsy/task-scheduler:1.1.a5c2bc
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: task-scheduler-service
spec:
  selector:
    app: task-scheduler
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: task-scheduler-route
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("task-scheduler.sytko.de")
      kind: Rule
      services:
        - name: task-scheduler-service
          port: 8080