name: TaskScheduler-BuildDeploy

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  REPO: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version
        run: |
          echo echo "APPVERSION=$(sed -n "s/\\s\{1,\}<Version>\([0-9]\{1,\}\.[0-9]\{1,\}\).*<\/Version>/\1/p" src/**/*.csproj).$GITHUB_SHA_SHORT" >> $GITHUB_ENV
          cat src/**/*.csproj

      - name: Publish
        run: |
          dotnet publish src/**/*.csproj --os linux --arch x64 --configuration Release /t:PublishContainer \
            -p:ContainerImageName=$REPO \
            -p:ContainerImageTags=$APPVERSION \
            -p:ContainerRegistry=$REGISTRY